// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var WithState$ReactTemplate = require("../withState/WithState.bs.js");

var WithCountState = WithState$ReactTemplate.Make(/* module */[]);

var component = ReasonReact.statelessComponent("WithState");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, Curry._2(WithCountState[/* make */1], 0, (function (param) {
                                var send = param[/* send */3];
                                var state = param[/* state */1];
                                return React.createElement("div", undefined, "Count: " + String(state), React.createElement("button", {
                                                onClick: (function () {
                                                    return Curry._1(send, /* Set */[state + 2 | 0]);
                                                  })
                                              }, "Inc"), React.createElement("button", {
                                                onClick: (function () {
                                                    return Curry._1(send, /* Set */[state - 3 | 0]);
                                                  })
                                              }, "Dec"));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.WithCountState = WithCountState;
exports.component = component;
exports.make = make;
/* WithCountState Not a pure module */
